// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATVQ9kGlC_3NKbiRgZ7lFLT2IlXlmuMac',
    appId: '1:366951136980:android:9b2f5f16d18105e8598541',
    messagingSenderId: '366951136980',
    projectId: 'flutter-yt-firebase-bkmax',
    databaseURL: 'https://flutter-yt-firebase-bkmax-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-yt-firebase-bkmax.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0uXkYXYP_vS2sszyoOZmRPKxZKotN9VA',
    appId: '1:366951136980:ios:ceb259d0f73508e6598541',
    messagingSenderId: '366951136980',
    projectId: 'flutter-yt-firebase-bkmax',
    databaseURL: 'https://flutter-yt-firebase-bkmax-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-yt-firebase-bkmax.firebasestorage.app',
    iosBundleId: 'com.example.coffeApp',
  );
}
